---
title: "Deep_based_statistics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this document, we make scripts to generate plots for Deep learning-based statistics comparison for the CRUKPAP (linear/interaction) cohort.

```{r load sources}
source("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Statistics_comparison/Settings.R")
source("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Statistics_comparison/Functions.R")
```

```{r load files (experiments results)}
load("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Statistics_comparison/R_files/DeepStat_trueX_fakeY_tables_perfx10.R")
```




```{r plots for Deep learning-based stats in the linear setting}

# Create data

df_done_RF_linear = df_perf_maker(table.perf.linear.Deep, list_target_fdr = list_target_fdr, stats_names  = c("swap", "deeppink", "swapint", "unweighted  " ), n.rep = 10)

df_power_fdr <- df_done_RF_linear[[1]]
df_fdp_fdr <- df_done_RF_linear[[2]] 
df_power_fdp <- df_done_RF_linear[[3]]


# Generate plots

graph_power_fdr <- ggplot(df_power_fdr, aes(x = target_fdr, y = power, color = KO, linetype = KO)) + 
  ylab("Power")+ 
  ylim(c(-0.25, 1.22)) +    
  xlab("Target FDR (q)") + 
  geom_ribbon(aes(ymin = power - std,ymax = power + std, group=KO, fill = KO), alpha = 0.15, colour = NA) + 
  #geom_point(size = 3, shape = 3)+ 
  geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
  scale_color_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B"))  +
  scale_fill_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B")) +
  scale_linetype_manual(values=c("dotdash", "longdash", "solid", "dotted")) +
  theme(axis.text.x = element_text(size = 22, face = "bold"),
  axis.title.x = element_text(size = 24),
  axis.title.y = element_text(size = 24),
  axis.text.y = element_text(size = 22, face = "bold"),
  #plot.subtitle = element_text(size = 20, face = "bold"),
  legend.title = element_blank(),
  legend.text = element_text(size = 26),
  legend.justification = c("right", "center"),
  legend.position = c(.7, 0.75),
  legend.key.width = unit(1.9,"cm"),
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
  plot.title = element_blank()
                   
        )
graph_power_fdr

graph_fdp_fdr <- ggplot(df_fdp_fdr, aes(x = target_fdr, y = fdp, color = KO, linetype = KO)) + 
   ylab("FDP")+ 
   xlab("Target FDR (q)") + 
   ylim(c(-0.25, 1.22)) + 
   geom_ribbon(aes(ymin = fdp - std,ymax = fdp + std, group = KO, fill = KO), alpha = 0.15, colour = NA) + 
   geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
   geom_abline(intercept = 0, slope = 1, color="black", linetype="dashed", linewidth = 1)+
   #labs(subtitle = "Linear") +
   scale_color_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B"))  +
   scale_fill_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B")) +
   scale_linetype_manual(values=c("dotdash", "longdash", "solid", "dotted")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = "none",
   plot.subtitle = element_text(size = 18, face = "bold"),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank()
        )

graph_fdp_fdr

graph_power_fdp <- ggplot(df_power_fdp, aes(x=fdp, y=power, color = KO)) + 
   ylab("Power")+ 
   xlab("FDP") + 
   ylim(c(-0.25, 1.22)) + 
   geom_point(aes(shape = KO), size = 3) +
   scale_shape_manual(values = c(17,19,9,15)) +  
   geom_ribbon(aes(ymin = power - std,ymax = power + std, group = KO, fill = KO), alpha = 0.15, colour = NA) +
   labs(title = "Power vs FDP, k = 10, X from X real") +
   scale_color_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B"))  +
   scale_fill_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.2, 0.7),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank()
        )
        
graph_power_fdp

# Combine plots

legend_power_fdr <- get_legend(graph_power_fdr)
graph_power_fdp_fdr <-ggarrange(
  graph_power_fdp,            
  ggarrange(graph_power_fdr, graph_fdp_fdr, ncol = 2, labels = c("(b) ", "(c)"), font.label = list(size = 16)), 
  nrow = 2, 
  labels = "(a)",
  font.label = list(size = 16)
  ) 

ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Statistics_comparison/Figures/SM_figure_7.png", height = 10, width = 14)

```




```{r plots for RF stats in the non linear setting}

# Create data frames

df_done_RF_nlinear = df_perf_maker(table.perf.nlinear.Deep, list_target_fdr = list_target_fdr, stats_names  = c("swap", "deeppink", "swapint", "unweighted  "), n.rep = 10)


df_power_fdr <- df_done_RF_nlinear[[1]]
df_fdp_fdr <- df_done_RF_nlinear[[2]] 
df_power_fdp <- df_done_RF_nlinear[[3]]

# Generate plots

graph_power_fdr <- ggplot(df_power_fdr, aes(x = target_fdr, y = power, color = KO, linetype = KO)) + 
  ylab("Power")+ 
  ylim(c(-0.25, 1.22)) +    
  xlab("Target FDR (q)") + 
  geom_ribbon(aes(ymin = power - std,ymax = power + std, group=KO, fill = KO), alpha = 0.15, colour = NA) + 
  #geom_point(size = 3, shape = 3)+ 
  geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
  scale_color_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B"))  +
  scale_fill_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B")) +
  scale_linetype_manual(values=c("dotdash", "longdash", "solid", "dotted")) +
  theme(axis.text.x = element_text(size = 22, face = "bold"),
  axis.title.x = element_text(size = 24),
  axis.title.y = element_text(size = 24),
  axis.text.y = element_text(size = 22, face = "bold"),
  #plot.subtitle = element_text(size = 20, face = "bold"),
  legend.title = element_blank(),
  legend.text = element_text(size = 26),
  legend.justification = c("right", "center"),
  legend.position = c(.7, 0.75),
  legend.key.width = unit(1.9,"cm"),
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
  plot.title = element_blank()
                   
        )
graph_power_fdr

graph_fdp_fdr <- ggplot(df_fdp_fdr, aes(x = target_fdr, y = fdp, color = KO, linetype = KO)) + 
   ylab("FDP")+ 
   xlab("Target FDR (q)") + 
   ylim(c(-0.25, 1.22)) + 
   geom_ribbon(aes(ymin = fdp - std,ymax = fdp + std, group = KO, fill = KO), alpha = 0.15, colour = NA) + 
   geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
   geom_abline(intercept = 0, slope = 1, color="black", linetype="dashed", linewidth = 1)+
   #labs(subtitle = "Linear") +
   scale_color_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B"))  +
   scale_fill_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B")) +
   scale_linetype_manual(values=c("dotdash", "longdash", "solid", "dotted")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = "none",
   plot.subtitle = element_text(size = 18, face = "bold"),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank()
        )

graph_fdp_fdr

graph_power_fdp <- ggplot(df_power_fdp, aes(x=fdp, y=power, color = KO)) + 
   ylab("Power")+ 
   xlab("FDP") + 
   ylim(c(-0.25, 1.22)) + 
   geom_point(aes(shape = KO), size = 3) +
   scale_shape_manual(values = c(17,19,9,15)) +  
   geom_ribbon(aes(ymin = power - std,ymax = power + std, group = KO, fill = KO), alpha = 0.15, colour = NA) +
   labs(title = "Power vs FDP, k = 10, X from X real") +
   scale_color_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B"))  +
   scale_fill_manual(values=c("#D65DB1", "#F6C1C0", "#A16AAB", "#6C5B7B")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.4, 0.7),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank()
        )
        
graph_power_fdp

# Combine plots

legend_power_fdr <- get_legend(graph_power_fdr)
graph_power_fdp_fdr <-ggarrange(
  graph_power_fdp,            
  ggarrange(graph_power_fdr, graph_fdp_fdr, ncol = 2, labels = c("(b) ", "(c)"), font.label = list(size = 16)), 
  nrow = 2, 
  labels = "(a)",
  font.label = list(size = 16)
  ) 

ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Statistics_comparison/Figures/SM_figure_10.png", height = 10, width = 14)

```

