
---
title: "graph_paper_stats_comparaison"
output: html_document
---

In this document, we make scripts to generate plots for the "final" statistics comparison for the three cohorts (CRUKPAP (linear/interaction), AEGIS, and Breast cancer). 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load sources}
source("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Statistics_comparison/Settings.R")
source("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Statistics_comparison/Functions.R")
```


# Experiments for the CRUKPAP cohort

```{r Statistics comparison in the linear setting, CRUKPAP cohort}

# load experiment results

load("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Statistics_comparison/R_files/compStat_trueX_fakeY_tables_perf.R")

# create data frames for graphical representation

df_done_synth_linear = df_perf_maker(table.perf.linear.comp, list_target_fdr = list_target_fdr, stats_names = c("LCD","EN-CD", "MLR","RF", "LPLR"), n.rep = 100, list_lambda=list_lambda)


df_power_fdr_tot <- df_done_synth_linear[[1]]
df_fdp_fdr_tot <- df_done_synth_linear[[2]] 
df_power_fdp <- df_done_synth_linear[[3]]

# Remove LASSO results in the graphical representation

df_power_fdr <- df_power_fdr_tot[df_power_fdr_tot$KO != "LPLR", ]
df_fdp_fdr <- df_fdp_fdr_tot[df_fdp_fdr_tot$KO != "LPLR", ]
df_power_fdp <- df_power_fdp[df_power_fdp$KO != "LPLR", ]

# CReate graphs 

graph_power_fdr <- ggplot(df_power_fdr, aes(x = target_fdr, y = power, color = KO)) + 
  ylab("Power")+ 
  ylim(c(-0.25, 1.22)) +    
  xlab("Target FDR (q)") + 
  geom_ribbon(aes(ymin = power - std,ymax = power + std, group=KO, fill = KO), alpha = 0.15, colour = NA) + 
  #geom_point(size = 3, shape = 3)+ 
  geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
  scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
  scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
  scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
  theme(axis.text.x = element_text(size = 22, face = "bold"),
  axis.title.x = element_text(size = 24),
  axis.title.y = element_text(size = 24),
  axis.text.y = element_text(size = 22, face = "bold"),
  plot.subtitle = element_text(size = 26, face = "bold"),
  legend.title = element_blank(),
  legend.text = element_text(size = 26),
  legend.justification = c("right", "center"),
  #legend.key.width = unit(0.9,"cm"),
  #legend.position = c(.4, 0.75),
  legend.position = "none",
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
  plot.title = element_blank(),
  plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
                   
        )
graph_power_fdr


graph_fdp_fdr <- ggplot(df_fdp_fdr, aes(x = target_fdr, y = fdp, color = KO)) + 
   ylab("FDP")+ 
   xlab("Target FDR (q)") + 
   ylim(c(-0.25, 1.22)) + 
   geom_ribbon(aes(ymin = fdp - std,ymax = fdp + std, group = KO, fill = KO), alpha = 0.15, colour = NA) + 
   #geom_point(size = 3, shape = 3)+ 
   geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
   geom_abline(intercept = 0, slope = 1, color="black", linetype="dashed", linewidth = 1) +
   #labs(subtitle = "Linear") +
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.35, 0.8),
   #legend.position = "none",
   legend.key.width = unit(1.5,"cm"),
   plot.subtitle = element_text(size = 18, face = "bold"),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        ) +   guides(linetype = guide_legend(override.aes = list(linewidth = 0.9)))

graph_fdp_fdr


graph_power_fdp <- ggplot(df_power_fdp, aes(x=fdp, y=power, color = KO)) + 
   ylab("Power")+ 
   xlab("FDP") + 
   ylim(c(-0.25, 1.22)) + 
   #ylim(c(-0.15, 1.20)) + 
   # geom_pointrange( aes(ymin = power-std, ymax = power+std),linewidth = 1)+
   geom_point(aes(shape = KO), size = 4) +
   scale_shape_manual(values = c(7, 15, 17, 18)) +  
   geom_ribbon(aes(ymin = power - std, ymax = power + std, group = KO, fill = KO), alpha = 0.15, colour = NA) +
   #geom_line(data = subset(df_power_fdp, KO == 'LASSO'), aes(group = KO))+
   #geom_line(aes(group = KO), linewidth = 1.5)+
   labs(title = "Power vs FDP, k = 10, X from X real") +
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.2, 0.7),
   #legend.key = element_rect(fill = "lightblue", color = NA),
  # Modifier la taille et la largeur des signes de la légende
    #legend.key.size = unit(1.5, "cm"),
    #legend.key.width = unit(1.5,"cm"),
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        )
        
graph_power_fdp

# Combined graphs

legend_power_fdr <- get_legend(graph_power_fdr)
graph_power_fdp_fdr <-ggarrange(
  graph_power_fdp,               
  ggarrange(graph_power_fdr, graph_fdp_fdr, ncol = 2, labels = c("(b) ", "(c) "), font.label = list(size = 18)), 
  nrow = 2, 
  labels = "(a) ",
  font.label = list(size = 18),
  legend = "top",
  heights = c(1.1, 1)
  ) 



ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Statistics_comparison/Figures/Figure_2.png", height = 10, width = 14)
```




```{r Statistics comparison in the interaction setting, CRUKPAP cohort}


# create data frames with the results 

df_done_synth_linear = df_perf_maker(table.perf.nlinear.comp, list_target_fdr = list_target_fdr, stats_names = c("LCD","EN-CD", "MLR","RF", "LPLR"), n.rep = 10, list_lambda=list_lambda)

df_power_fdr_tot <- df_done_synth_linear[[1]]
df_fdp_fdr_tot <- df_done_synth_linear[[2]] 
df_power_fdp <- df_done_synth_linear[[3]]


df_power_fdr <- df_power_fdr_tot[df_power_fdr_tot$KO != "LPLR", ]
df_fdp_fdr <- df_fdp_fdr_tot[df_fdp_fdr_tot$KO != "LPLR", ]
df_power_fdp <- df_power_fdp[df_power_fdp$KO != "LPLR", ]


# Create graphical representations 

graph_power_fdr <- ggplot(df_power_fdr, aes(x = target_fdr, y = power, color = KO)) + 
  ylab("Power")+ 
  ylim(c(-0.25, 1.22)) +    
  xlab("Target FDR (q)") + 
  geom_ribbon(aes(ymin = power - std,ymax = power + std, group=KO, fill = KO), alpha = 0.15, colour = NA) + 
  geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
  scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
  scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
  scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
  theme(axis.text.x = element_text(size = 22, face = "bold"),
  axis.title.x = element_text(size = 24),
  axis.title.y = element_text(size = 24),
  axis.text.y = element_text(size = 22, face = "bold"),
  plot.subtitle = element_text(size = 26, face = "bold"),
  legend.title = element_blank(),
  legend.text = element_text(size = 26),
  legend.justification = c("right", "center"),
  legend.key.width = unit(1.5,"cm"),
   legend.position = c(.35, 0.8),
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
  plot.title = element_blank(),
  plot.margin = unit(c(0.6, 0., 0., 0.6), "cm")
                   
        ) +   guides(linetype = guide_legend(override.aes = list(linewidth = 0.9)))
graph_power_fdr

ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Statistics_comparison/Figures/Figure_2.png", height = 5, width = 10)

graph_fdp_fdr <- ggplot(df_fdp_fdr, aes(x = target_fdr, y = fdp, color = KO)) + 
   ylab("FDP")+ 
   xlab("Target FDR (q)") + 
   ylim(c(-0.25, 1.22)) + 
   geom_ribbon(aes(ymin = fdp - std,ymax = fdp + std, group = KO, fill = KO), alpha = 0.15, colour = NA) + 
   geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
   geom_abline(intercept = 0, slope = 1, color="black", linetype="dashed", linewidth = 1)+
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = "none",
   plot.subtitle = element_text(size = 18, face = "bold"),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        )

graph_fdp_fdr

graph_power_fdp <- ggplot(df_power_fdp, aes(x=fdp, y=power, color = KO)) + 
   ylab("Power")+ 
   xlab("FDP") + 
   ylim(c(-0.25, 1.22)) + 
   geom_point(aes(shape = KO), size = 4) +
   scale_shape_manual(values = c(7, 15, 17, 18)) + 
   geom_ribbon(aes(ymin = power - std, ymax = power + std, group = KO, fill = KO), alpha = 0.15, colour = NA) +
   #geom_line(data = subset(df_power_fdp, KO == 'LASSO'), aes(group = KO))+
   labs(title = "Power vs FDP, k = 10, X from X real") +
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.2, 0.7),
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        )
        
graph_power_fdp


legend_power_fdr <- get_legend(graph_power_fdr)
graph_power_fdp_fdr <-ggarrange(
  graph_power_fdp,              
  ggarrange(graph_power_fdr, graph_fdp_fdr, ncol = 2, labels = c("(b) ", "(c) "), font.label = list(size = 18)), 
  nrow = 2, 
  labels = "(a) ",
  font.label = list(size = 18),
  legend = "top",
  heights = c(1.1, 1)
  ) 
ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Statistics_comparison/Figures/Figure_3_all.png", height = 10, width = 14)

graph_fdp_fdr_bis <- ggplot(df_fdp_fdr, aes(x = target_fdr, y = fdp, color = KO)) + 
   ylab("FDP")+ 
   xlab("Target FDR (q)") + 
   ylim(c(-0.25, 1.22)) + 
   geom_ribbon(aes(ymin = fdp - std,ymax = fdp + std, group = KO, fill = KO), alpha = 0.15, colour = NA) + 
   geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
   geom_abline(intercept = 0, slope = 1, color="black", linetype="dashed", linewidth = 1)+
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.key.width = unit(1.5,"cm"),
   legend.position = c(.3, 0.8),
   plot.subtitle = element_text(size = 18, face = "bold"),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        )

graph_fdp_fdr

legend_power_fdr <- get_legend(graph_power_fdr)
graph_power_fdp_fdr <-ggarrange(graph_power_fdp, graph_fdp_fdr_bis, nrow = 2, labels = c("(a) ", "(b) "), font.label = list(size = 18)) 
ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Statistics_comparison/Figures/SM_figure_8.png", height = 10, width = 14)
```




# For breast cancer data



```{r Statistics comparison in the linear setting, Breast cancer data}

# load results

load("/home/julie/Documents/Paper_codes/New_cohorts_EXPERIMENTS/BC/R_files/table_perf_statistic_comparaison_3e_cohorte.R")

# create data frame

df_done_synth_linear = df_perf_maker(table.perf.linear.comp, list_target_fdr = list_target_fdr, stats_names = c("LCD","EN-CD", "MLR","RF", "LPLR"), n.rep = 100, list_lambda=list_lambda)


df_power_fdr_tot <- df_done_synth_linear[[1]]
df_fdp_fdr_tot <- df_done_synth_linear[[2]] 
df_power_fdp <- df_done_synth_linear[[3]]


df_power_fdr <- df_power_fdr_tot[df_power_fdr_tot$KO != "LPLR", ]
df_fdp_fdr <- df_fdp_fdr_tot[df_fdp_fdr_tot$KO != "LPLR", ]
df_power_fdp <- df_power_fdp[df_power_fdp$KO != "LPLR", ]

# CReate plots

graph_power_fdr <- ggplot(df_power_fdr, aes(x = target_fdr, y = power, color = KO)) + 
  ylab("Power")+ 
  ylim(c(-0.25, 1.22)) +    
  xlab("Target FDR (q)") + 
  geom_ribbon(aes(ymin = power - std,ymax = power + std, group=KO, fill = KO), alpha = 0.15, colour = NA) + 
  geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
  scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
  scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
  scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
  theme(axis.text.x = element_text(size = 22, face = "bold"),
  axis.title.x = element_text(size = 24),
  axis.title.y = element_text(size = 24),
  axis.text.y = element_text(size = 22, face = "bold"),
  plot.subtitle = element_text(size = 26, face = "bold"),
  legend.title = element_blank(),
  legend.text = element_text(size = 26),
  legend.justification = c("right", "center"),
  legend.position = "none",
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
  plot.title = element_blank(),
  plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
                   
        )
graph_power_fdr

graph_fdp_fdr <- ggplot(df_fdp_fdr, aes(x = target_fdr, y = fdp, color = KO)) + 
   ylab("FDP")+ 
   xlab("Target FDR (q)") + 
   ylim(c(-0.25, 1.22)) + 
   geom_ribbon(aes(ymin = fdp - std,ymax = fdp + std, group = KO, fill = KO), alpha = 0.15, colour = NA) + 
   geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
   geom_abline(intercept = 0, slope = 1, color="black", linetype="dashed", linewidth = 1) +
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.35, 0.8),
   legend.key.width = unit(1.5,"cm"),
   plot.subtitle = element_text(size = 18, face = "bold"),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        ) +   guides(linetype = guide_legend(override.aes = list(linewidth = 0.9)))

graph_fdp_fdr

graph_power_fdp <- ggplot(df_power_fdp, aes(x=fdp, y=power, color = KO)) + 
   ylab("Power")+ 
   xlab("FDP") + 
   ylim(c(-0.25, 1.22)) + 
   geom_point(aes(shape = KO), size = 4) +
   scale_shape_manual(values = c(7, 15, 17, 18)) +
   geom_ribbon(aes(ymin = power - std, ymax = power + std, group = KO, fill = KO), alpha = 0.15, colour = NA) +
   #geom_line(data = subset(df_power_fdp, KO == 'LASSO'), aes(group = KO))+
   labs(title = "Power vs FDP, k = 10, X from X real") +
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.2, 0.7),
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        )
        
graph_power_fdp

# Combined plots

legend_power_fdr <- get_legend(graph_power_fdr)
graph_power_fdp_fdr <-ggarrange(
  graph_power_fdp,                
  ggarrange(graph_power_fdr, graph_fdp_fdr, ncol = 2, labels = c("(b) ", "(c) "), font.label = list(size = 18)), 
  nrow = 2, 
  labels = "(a) ",
  font.label = list(size = 18),
  legend = "top",
  heights = c(1.1, 1)
  ) 

ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Statistics_comparison/Figures/SM_figure_24.png", height = 10, width = 14)
```


# For AEGIS




```{r Statistics comparison in the linear setting, AEGIS cohort}

# load results 

load("/home/julie/Documents/Paper_codes/New_cohorts_EXPERIMENTS/AEGIS/R_files/table_perf_statistic_comparaison_2e_cohorte.R")

# Create data frame

df_done_synth_linear = df_perf_maker(table.perf.linear.comp, list_target_fdr = list_target_fdr, stats_names = c("LCD","EN-CD", "MLR","RF", "LPLR"), n.rep = 100, list_lambda=list_lambda)

df_power_fdr_tot <- df_done_synth_linear[[1]]
df_fdp_fdr_tot <- df_done_synth_linear[[2]] 
df_power_fdp <- df_done_synth_linear[[3]]


df_power_fdr <- df_power_fdr_tot[df_power_fdr_tot$KO != "LPLR", ]
df_fdp_fdr <- df_fdp_fdr_tot[df_fdp_fdr_tot$KO != "LPLR", ]
df_power_fdp <- df_power_fdp[df_power_fdp$KO != "LPLR", ]


# Generate performance plots

graph_power_fdr <- ggplot(df_power_fdr, aes(x = target_fdr, y = power, color = KO)) + 
  ylab("Power")+ 
  ylim(c(-0.25, 1.22)) +    
  xlab("Target FDR (q)") + 
  geom_ribbon(aes(ymin = power - std,ymax = power + std, group=KO, fill = KO), alpha = 0.15, colour = NA) + 
  geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
  scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
  scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
  scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
  theme(axis.text.x = element_text(size = 22, face = "bold"),
  axis.title.x = element_text(size = 24),
  axis.title.y = element_text(size = 24),
  axis.text.y = element_text(size = 22, face = "bold"),
  plot.subtitle = element_text(size = 26, face = "bold"),
  legend.title = element_blank(),
  legend.text = element_text(size = 26),
  legend.justification = c("right", "center"),
  legend.position = "none",
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
  plot.title = element_blank(),
  plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
                   
        )
graph_power_fdr


# Idem FDP vs FDR


graph_fdp_fdr <- ggplot(df_fdp_fdr, aes(x = target_fdr, y = fdp, color = KO)) + 
   ylab("FDP")+ 
   xlab("Target FDR (q)") + 
   ylim(c(-0.25, 1.22)) + 
   geom_ribbon(aes(ymin = fdp - std,ymax = fdp + std, group = KO, fill = KO), alpha = 0.15, colour = NA) + 
   geom_line(aes(group = KO, linetype = KO), linewidth = 1.5)+
   geom_abline(intercept = 0, slope = 1, color="black", linetype="dashed", linewidth = 1) +
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   scale_linetype_manual(values=c("dotdash", "longdash", "solid", "twodash")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.35, 0.8),
   #legend.position = "none",
   legend.key.width = unit(1.5,"cm"),
   plot.subtitle = element_text(size = 18, face = "bold"),
   panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        ) +   guides(linetype = guide_legend(override.aes = list(linewidth = 0.9)))

graph_fdp_fdr


# Power FDP

graph_power_fdp <- ggplot(df_power_fdp, aes(x=fdp, y=power, color = KO)) + 
   ylab("Power")+ 
   xlab("FDP") + 
   ylim(c(-0.25, 1.22)) + 
   geom_point(aes(shape = KO), size = 4) +
   scale_shape_manual(values = c(7, 15, 17, 18)) + 
   geom_ribbon(aes(ymin = power - std, ymax = power + std, group = KO, fill = KO), alpha = 0.15, colour = NA) +
   #geom_line(data = subset(df_power_fdp, KO == 'LASSO'), aes(group = KO))+
   labs(title = "Power vs FDP, k = 10, X from X real") +
   scale_color_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520"))  +
   scale_fill_manual(values=c("#8FAD86", "#17becf", "#7f7f7f", "#DAA520")) +
   theme(axis.text.x = element_text(size = 22, face = "bold"),
   axis.title.x = element_text(size = 24),
   axis.title.y = element_text(size = 24),
   axis.text.y = element_text(size = 22, face = "bold"),
   legend.title = element_blank(),
   legend.text = element_text(size = 26),
   legend.justification = c("right", "center"),
   legend.position = c(.2, 0.7),
  panel.background = element_rect(fill = "#F6F6F6"),
                   panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
                   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
   plot.title = element_blank(),
   plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
        )
        
graph_power_fdp

# Combined plots

legend_power_fdr <- get_legend(graph_power_fdr)
graph_power_fdp_fdr <-ggarrange(
  graph_power_fdp,               
  ggarrange(graph_power_fdr, graph_fdp_fdr, ncol = 2, labels = c("(b) ", "(c) "), font.label = list(size = 18)), 
  nrow = 2, 
  labels = "(a) ",
  font.label = list(size = 18),
  legend = "top",
  heights = c(1.1, 1)
  ) 


ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Statistics_comparison/Figures/SM_figure_22.png", height = 10, width = 14)
```









