---
title: "Stability_graph_paper"
output: html_document
---
Goal : Illustrate the impact of KO methods stochasticity on features selection. Study the effect of KOPI on stability (compare to KO). 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## KOPI effect ##


```{r load sources and comparison data}

source("/home/julie/Documents/Paper_codes/CUKPAP_EXPERIMENTS/Stability/Settings.R")
source("/home/julie/Documents/Paper_codes/CUKPAP_EXPERIMENTS/Stability/Functions.R")

load("/home/julie/Documents/Paper_codes/CUKPAP_EXPERIMENTS/Stability/R_files/table.selected_genes_no_cv_Vanilla.R")
load("/home/julie/Documents/Paper_codes/CUKPAP_EXPERIMENTS/Stability/R_files/table.selected_genes_no_cv_KOPI.R")
```


```{r Selection proportion histograms for KOPI}

list_non_null <- which(beta!=0)
true_genes <- rep("False discoveries ", ncol(X_real))
true_genes[ which(beta!=0)] <- "True genes"



prop_selection_0.2 <- rowSums(table.selected_genes.KOPI_0.2)
prop_selection_0.5 <- rowSums(table.selected_genes.KOPI_0.5)


prop_selection_0.2_0 <- prop_selection_0.2[ !prop_selection_0.2 == 0]
prop_selection_0.5_0 <- prop_selection_0.5[ !prop_selection_0.5 == 0]


data_0.2 <- data.frame(freq = prop_selection_0.2_0/100, status = as.factor(true_genes[ !prop_selection_0.2 == 0]))

hist_KOPI0.2 <- ggplot(data_0.2, aes(x = freq, fill = status)) +
  geom_histogram(binwidth = 0.01, color = "black" ) +
  coord_cartesian(xlim = c(0, 1)) + 
  ylim(0, 11) +
  labs(title = "Selection proportion of genes selected more than once",
       x = "Selection frequency",
       y = "Number of genes") +
 theme(axis.text.x = element_text(size = 20, face = "bold"),
        axis.title.x = element_text(size = 24, vjust = -2),
        axis.title.y = element_text(size = 24, vjust = +3),
        axis.text.y = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(hjust = 0),
        plot.caption = element_text(size = 12, face = "bold"),
        panel.background = element_rect(fill = "#F6F6F6"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "white"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "white"),
        plot.title = element_blank(),
        legend.position = "none",
        legend.text = element_text(size = 20),  
        legend.title = element_blank()  , 
        plot.margin = unit(c(0.3, 0.3, 0.3, 0.3), "inches")
  ) +
  scale_fill_manual(values = c("#FF5733",  "#BDDF8E", "#FFFF66")) 
hist_KOPI0.2

data_0.5 <- data.frame(freq = prop_selection_0.5_0/100, status = as.factor(true_genes[ !prop_selection_0.5 == 0]))

hist_KOPI0.5 <- ggplot(data_0.5, aes(x = freq, fill = status)) +
  geom_histogram(binwidth = 0.01, color = "black" ) +
  coord_cartesian(xlim = c(0, 1)) + 
  ylim(0, 11) +
  labs(title = "Selection proportion of genes selected more than once",
       x = "Selection frequency",
       y = "Number of genes") +
 theme(axis.text.x = element_text(size = 20, face = "bold"),
        axis.title.x = element_text(size = 24, vjust = -2),
        axis.title.y = element_text(size = 24, vjust = +3),
        axis.text.y = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(hjust = 0),
        plot.caption = element_text(size = 12, face = "bold"),
        panel.background = element_rect(fill = "#F6F6F6"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "white"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "white"),
        plot.title = element_blank(),
        legend.position = "none",
        legend.text = element_text(size = 20),  
        legend.title = element_blank()  , 
        plot.margin = unit(c(0.3, 0.3, 0.3, 0.3), "inches")
  ) +
  scale_fill_manual(values = c("#008899", "#FF5733", "#FFFF66")) 

hist_KOPI0.5


```


```{r Selection proportion histograms for the KO framework}


prop_selection_0.2 <- rowSums(table.selected_genes.Vanilla_0.2)
prop_selection_0.5 <- rowSums(table.selected_genes.Vanilla_0.5)

prop_selection_0.2_0 <- prop_selection_0.2[ !prop_selection_0.2 == 0]
prop_selection_0.5_0 <- prop_selection_0.5[ !prop_selection_0.5 == 0]



data_0.2 <- data.frame(freq = prop_selection_0.2_0/100, status = as.factor(true_genes[ !prop_selection_0.2 == 0]))

hist_0.2 <- ggplot(data_0.2, aes(x = freq, fill = status)) +
  geom_histogram(binwidth = 0.01, color = "black") +
  coord_cartesian(xlim = c(0, 1)) + 
  ylim(0, 11) +
  labs(title = "Selection proportion of genes selected more than once",
       x = "Selection frequency",
       y = "Number of genes") +
 theme(axis.text.x = element_text(size = 20, face = "bold"),
        axis.title.x = element_text(size = 24, vjust = -2),
        axis.title.y = element_text(size = 24, vjust = +3),
        axis.text.y = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(hjust = 0),
        plot.caption = element_text(size = 12, face = "bold"),
        panel.background = element_rect(fill = "#F6F6F6"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "white"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "white"),
        plot.title = element_blank(),
        #legend.position = c(.75, 0.7),
        legend.position = "top",
        #legend.position = "none",
        legend.text = element_text(size = 20),  
        legend.title = element_blank()  , 
        plot.margin = unit(c(0.3, 0.3, 0.3, 0.3), "inches")
  ) +
  scale_fill_manual(values = c("#17becf", "#FF5733", "#FFFF66")) # Define colors for different statuses

hist_0.2

data_0.5 <- data.frame(freq = prop_selection_0.5_0/100, status = as.factor(true_genes[ !prop_selection_0.5 == 0]))

hist_0.5 <- ggplot(data_0.5, aes(x = freq, fill = status)) +
  geom_histogram(binwidth = 0.01, color = "black") +
  coord_cartesian(xlim = c(0, 1)) + 
  ylim(0, 11) +
  labs(title = "Selection proportion of genes selected more than once",
       x = "Selection frequency",
       y = "Number of genes") +
 theme(axis.text.x = element_text(size = 20, face = "bold"),
        axis.title.x = element_text(size = 24, vjust = -2),
        axis.title.y = element_text(size = 24, vjust = +3),
        axis.text.y = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(hjust = 0),
        plot.caption = element_text(size = 12, face = "bold"),
        panel.background = element_rect(fill = "#F6F6F6"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "white"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "white"),
        plot.title = element_blank(),
        #legend.position = "none",
        #legend.position = c(.75, 0.7),
        legend.position = "top",
        legend.text = element_text(size = 20),  
        legend.title = element_blank()  , 
        plot.margin = unit(c(0.3, 0.3, 0.3, 0.3), "inches")
  ) +
  scale_fill_manual(values = c("#008899", "#FF5733", "#FFFF66")) 

hist_0.5

```







```{r}

graph_0.2 <- ggarrange(hist_0.2, hist_KOPI0.2, ncol = 2, labels = c("(a) : Vanilla KO, q = 0.2 ", "(b) : KOPI, q = 0.2"), label.x = 0.2, label.y = 0.9, common.legend = TRUE, font.label = list(size = 18), legend = "top") 


graph_0.5 <- ggarrange(hist_0.5, hist_KOPI0.5, ncol = 2, labels = c("(c) : Vanilla KO, q = 0.5 ", "(d) : KOPI, q = 0.5"), label.x = 0.2, label.y = 0.9, common.legend = TRUE, font.label = list(size = 18), legend = "top") 


combined_graph <- ggarrange(graph_0.2, graph_0.5, ncol = 1, labels = NULL)

ggsave(file = "/home/julie/Documents/Paper_codes/Paper_graphs/Stability/Figures/SM_figure_12.png", plot = combined_graph, height = 14, width = 15)

```

