---
title: "Boxplots_classification_performance"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Wilcoxon_vs_KO_vs_LASSO_vs_KOPI/Prediction/R_files/table.perf.classif.RData")
```

```{r Accuracy plots}


perf.metric <- 5 #accuracy metric
vec.meth.names <- c("Ridge", "GLM", "SVM", "XGB")


for (i in 1:4){
  classif.model <- i
  perf.accuracy <- c(unlist(perf.KO.0.2[[classif.model]][perf.metric, ]), unlist(perf.KO.0.5[[classif.model]][perf.metric, ]), unlist(perf.KOPI.0.2[[classif.model]][perf.metric, ]), unlist(perf.KOPI.0.5[[classif.model]][perf.metric, ]), unlist(perf.lambda.min[[classif.model]][perf.metric, ]), unlist(perf.lambda.oracle[[classif.model]][perf.metric, ]))
  
  df_accuracy <- data.frame(perf = perf.accuracy, Method = rep(c("KO, q = 0.2", "KO, q = 0.5", "KOPI, q = 0.2", "KOPI, q = 0.5", "\u3BB(min)", "\u3BB(oracle)"), each = 1000)) %>% subset(perf != "remove") #%>% subset(perf != "0")
  df_accuracy$perf <- as.numeric(df_accuracy$perf)
  
  
  ggplot(df_accuracy, aes(x=Method, y=perf, fill=Method)) + 
      geom_boxplot(alpha=0.5) +
      ylab("Accuracy")+ 
      scale_fill_manual(values=c("#17becf", "#008899", "#95b0b4", "#4e686b", "#7c6fb0", "#b2a3e8")) +
      #scale_x_discrete(labels = c("KO, q = 0.2", "KO, q = 0.5", "KOPI, q = 0.2", "KOPI, q = 0.5", "lambda[min]", "lambda[oracle]"))+
      theme(axis.text.x = element_text(size = 22, face = "bold"),
       axis.title.x = element_text(size = 24),
       axis.title.y = element_text(size = 24),
       axis.text.y = element_text(size = 22, face = "bold"),
       legend.title = element_blank(),
       legend.text = element_text(size = 26),
       legend.justification = c("right", "center"),
       legend.position = "none",
       panel.background = element_rect(fill = "#F6F6F6"),
                       panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                    colour = "white"), 
                       panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                    colour = "white"),
       plot.title = element_blank(),
       plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
            )
  
  
  ggsave(file = str_glue("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Wilcoxon_vs_KO_vs_LASSO_vs_KOPI/Prediction/Figures/boxplot_accuracy_",vec.meth.names[i],".png"), height = 10, width = 14)
    
}



```



