---
title: "Mean_classification_performance"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r source R files}
source('/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Wilcoxon_vs_KO_vs_LASSO_vs_KOPI/Settings.R')
source('/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Wilcoxon_vs_KO_vs_LASSO_vs_KOPI/Functions.R')
```

```{r}
load("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Wilcoxon_vs_KO_vs_LASSO_vs_KOPI/Prediction/R_files/table.perf.classif.RData")
```

```{r Accuracy plots}

perf.metric <- 5 # accuracy metric
vec.meth.names <- c("Ridge", "GLM", "SVM", "XGB")

for (i in 1:1) {
  classif.model <- i
  
  lassif.model <- i
  perf.accuracy <- c(unlist(perf.KO.0.2[[classif.model]][perf.metric, ]), unlist(perf.KO.0.5[[classif.model]][perf.metric, ]), unlist(perf.KOPI.0.2[[classif.model]][perf.metric, ]), unlist(perf.KOPI.0.5[[classif.model]][perf.metric, ]), unlist(perf.lambda.min[[classif.model]][perf.metric, ]), unlist(perf.lambda.oracle[[classif.model]][perf.metric, ]))
  
  df_accuracy <- data.frame(perf = perf.accuracy, Method = rep(c("KO, q = 0.2", "KO, q = 0.5", "KOPI, q = 0.2", "KOPI, q = 0.5", "\u3BB(min)", "\u3BB(oracle)"), each = 1000)) %>% subset(perf != "remove") #%>% subset(perf != "0")
  df_accuracy$perf <- as.numeric(df_accuracy$perf)
  
 
  df_summary <- df_accuracy %>% group_by(Method) %>% summarise(mean_perf = mean(perf, na.rm = TRUE),
      sd_perf = sd(perf, na.rm = TRUE)
    )
  
  ggplot(df_summary, aes(x = Method, y = mean_perf, color = Method)) +
    geom_pointrange(aes(ymin = mean_perf - sd_perf, ymax = mean_perf + sd_perf), size = 1.2, fatten = 2) +
    ylab("Accuracy") +
    xlab("") +
    scale_color_manual(values = c("#17becf", "#008899", "#95b0b4","#4e686b", "#7c6fb0", "#b2a3e8")) +
    coord_cartesian(ylim = c(0, 1.1)) +
    theme_minimal(base_size = 18) +
    theme(
      axis.text.x = element_text(size = 22, face = "bold"),
      axis.title.x = element_text(size = 24),
      axis.title.y = element_text(size = 24),
      axis.text.y = element_text(size = 22, face = "bold"),
      legend.position = "none",
      panel.grid.major = element_line(size = 0.5, colour = "white"),
      panel.background = element_rect(fill = "#F6F6F6"),
      plot.margin = unit(c(0.6, 0.2, 0.2, 0.6), "cm")
    )

  ggsave(file = str_glue("/home/julie/Documents/Paper_codes/CRUKPAP_EXPERIMENTS/Wilcoxon_vs_KO_vs_LASSO_vs_KOPI/Prediction/Figures/Mean_accuracy_",vec.meth.names[i],".png"), height = 10, width = 14)
    
}



```



